// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using crosam.Data;

namespace crosam.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210108035537_MigracionSiembraServicios")]
    partial class MigracionSiembraServicios
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("crosam.Models.BouyType", b =>
                {
                    b.Property<int>("BouyTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BouyTypeName")
                        .HasColumnType("TEXT");

                    b.HasKey("BouyTypeId");

                    b.ToTable("BouyType");
                });

            modelBuilder.Entity("crosam.Models.Cuelga", b =>
                {
                    b.Property<int>("CuelgaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CuelgaLenght")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CuelgaTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CuelgaId");

                    b.HasIndex("CuelgaTypeId");

                    b.ToTable("Cuelga");
                });

            modelBuilder.Entity("crosam.Models.CuelgaType", b =>
                {
                    b.Property<int>("CuelgaTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CuelgaTypeName")
                        .HasColumnType("TEXT");

                    b.HasKey("CuelgaTypeId");

                    b.ToTable("CuelgaType");
                });

            modelBuilder.Entity("crosam.Models.Location", b =>
                {
                    b.Property<int>("LocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocationName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.HasKey("LocationID");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("crosam.Models.Seed", b =>
                {
                    b.Property<int>("SeedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SeedSize")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("SeedId");

                    b.ToTable("Seed");
                });

            modelBuilder.Entity("crosam.Models.Seeder", b =>
                {
                    b.Property<int>("SeederID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeederName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.HasKey("SeederID");

                    b.HasIndex("LocationID");

                    b.ToTable("Seeder");
                });

            modelBuilder.Entity("crosam.Models.ServicioFlete", b =>
                {
                    b.Property<int>("ServicioFleteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServicioFleteName")
                        .HasColumnType("TEXT");

                    b.HasKey("ServicioFleteId");

                    b.ToTable("ServicioFlete");
                });

            modelBuilder.Entity("crosam.Models.Siembras", b =>
                {
                    b.Property<int>("SiembraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GastoFlete")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GastoSemilla")
                        .HasColumnType("TEXT");

                    b.Property<int>("NroGuia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Recepcion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServicioFleteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorUnidad")
                        .HasColumnType("TEXT");

                    b.HasKey("SiembraId");

                    b.HasIndex("ServicioFleteId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Siembras");
                });

            modelBuilder.Entity("crosam.Models.Sow", b =>
                {
                    b.Property<int>("SowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BouyTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadColgado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CuelgaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CuelgaTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("Linea")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeedId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeederId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubstratumId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SowId");

                    b.HasIndex("BouyTypeId");

                    b.HasIndex("CuelgaId");

                    b.HasIndex("CuelgaTypeId");

                    b.HasIndex("SeedId");

                    b.HasIndex("SeederId");

                    b.HasIndex("SubstratumId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Sow");
                });

            modelBuilder.Entity("crosam.Models.Substratum", b =>
                {
                    b.Property<int>("SubstratumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubstratumName")
                        .HasColumnType("TEXT");

                    b.HasKey("SubstratumId");

                    b.ToTable("Substratum");
                });

            modelBuilder.Entity("crosam.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SupplierName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.HasKey("SupplierId");

                    b.HasIndex("LocationId");

                    b.ToTable("Supplier");
                });

            modelBuilder.Entity("crosam.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<char>("Sex")
                        .HasColumnType("TEXT")
                        .HasMaxLength(1);

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50)
                        .HasDefaultValue("0");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("crosam.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("crosam.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("crosam.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("crosam.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("crosam.Models.Cuelga", b =>
                {
                    b.HasOne("crosam.Models.CuelgaType", "CuelgaType")
                        .WithMany()
                        .HasForeignKey("CuelgaTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("crosam.Models.Seeder", b =>
                {
                    b.HasOne("crosam.Models.Location", "Location")
                        .WithMany("seeders")
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("crosam.Models.Siembras", b =>
                {
                    b.HasOne("crosam.Models.ServicioFlete", "ServicioFlete")
                        .WithMany("Siembras")
                        .HasForeignKey("ServicioFleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("crosam.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("crosam.Models.Sow", b =>
                {
                    b.HasOne("crosam.Models.BouyType", "BouyType")
                        .WithMany("Sows")
                        .HasForeignKey("BouyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("crosam.Models.Cuelga", "Cuelga")
                        .WithMany("Sows")
                        .HasForeignKey("CuelgaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("crosam.Models.CuelgaType", "CuelgaType")
                        .WithMany("Sows")
                        .HasForeignKey("CuelgaTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("crosam.Models.Seed", "Seed")
                        .WithMany("Sows")
                        .HasForeignKey("SeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("crosam.Models.Seeder", "Seeder")
                        .WithMany("Sows")
                        .HasForeignKey("SeederId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("crosam.Models.Substratum", "Substratum")
                        .WithMany("Sows")
                        .HasForeignKey("SubstratumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("crosam.Models.Supplier", "Supplier")
                        .WithMany("Sows")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("crosam.Models.Supplier", b =>
                {
                    b.HasOne("crosam.Models.Location", "Location")
                        .WithMany("Suppliers")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
